### ISSUE TITLE
Update PHP

### ISSUE THREAD

**Issue by AndreaBarghigiani** [welaika/docker-wordmove#10]
Hi all,
I am usign with great satisfaction your docker image but I would like to know if you plan to update the PHP version because WP CLI does not work anymore with the 5.5.9 that is installed by default with it.

Maybe even update Ubuntu but this is another issue.

Thank you for reading and for the help.

**Comment by alessandro-fazzi** [comment]
Oh! 5.5.9 is absolutely out of our mind actually!
I'd consider mandatory to update to PHP 7.2 :)

Thanks for pointing that out.

@simonbland would you have the time to go on with this update or should I take care of it?

Lemme know and eventually re-assign it to me 👍

**Comment by alessandro-fazzi** [comment]
We must bring this together with #2

**Comment by AndreaBarghigiani** [comment]
Thanks @pioneerskies for answer so quickly.

I thought to edit the Dockerfile upgrading also Ubuntu to 16.04 but I do not use Linux (I'm on OSX) and I do not know which packages will comes along.

I hope this is not something difficult to do.

**Comment by alessandro-fazzi** [comment]
I think the latest LTS would be ok to go.

Should not be hard, but anyway is mandatory to not become too much obsolete 💪

**Comment by alessandro-fazzi** [comment]
Hey @AndreaBarghigiani ,

I've just tried to build from `latest`, to login and to use `wp-cli` from there. I have not noticed any problem. Would you mind to point me to the issue you found and/or to `wp-cli`'s doc where I could find info about requirements?

Thanks in advance

**Comment by AndreaBarghigiani** [comment]
Hi @pioneerskies,
there has been a bump in the [WordPress requirements since the 5.2 where the minimum PHP version is the 5.6.20](https://wordpress.org/news/2019/04/minimum-php-version-update/) (soon it will be 7+).

I've tryed right now to build an environment with WordPress 5.0.2 and if I use `wp search-replace` (for example) with it will run smoothly but once updated WordPress to the latest version, if I try to run the same command I get this:
`Il server sta utilizzando PHP versione 5.5.9-1ubuntu4.27 ma WordPress 5.2 richiede almeno la versione 5.6.20.`

If you need more information please ask.

Thank you for your time.

**Comment by alessandro-fazzi** [comment]
@AndreaBarghigiani `welaika/wordmove:php7` is out.

I've not changed the latest because I've done a lot of changes and need someone who could test it before to do the switch.

Old version will remain frozen as `welaika/wordmove:php5`.

Waiting your feedback before to close.

**Comment by simonbland** [comment]
> Oh! 5.5.9 is absolutely out of our mind actually!
> I'd consider mandatory to update to PHP 7.2 :)
> 
> Thanks for pointing that out.
> 
> @simonbland would you have the time to go on with this update or should I take care of it?
> 
> Lemme know and eventually re-assign it to me 👍

Hi @pioneerskies,

Thank you for taking care of this. I'm not that available these days unfortunately. Sorry about this.

**Comment by alessandro-fazzi** [comment]
Hey @simonbland no worries at all. Today I gave up on going to the countryside due to an horrible rainy day, so I've found a bit of time.

I followed all our past discussions about tags/naming/strategies; if you have any kind of advice you're totally welcome.

Bye bye and take care.

**Comment by simonbland** [comment]
Hi @pioneerskies,

I wish you some good weather next weekend then ;)

I saw the tags you pushed today, according to what we discussed in #2. It's great like this for me!

Cheers

**Comment by AndreaBarghigiani** [comment]
Hi @pioneerskies,
the PHP issue is now gone, if I run `php -v` here's what I get:
```
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```
But now I've another problem because it looks like this new image does not read the `volumes` and it jumps me on the `/html` folder.

I've another problem but I'll open a different ticket to keep things separated.

Thank you again,
Andrea
