### ISSUE TITLE
Testing Alpine as a drop-in replacement for php7

### ISSUE THREAD

**Issue by Gadgitmatic** [welaika/docker-wordmove#13]
I saw the Alpine Docker #3 image was in need of testing and decided to give it a shot and contribute some testing feedback to the team. 
I am using the Alpine tag as a drop-in replacement on a working docker-compose setup previously using php7 image. Here are a few of the errors I've come across so far. 

**Movile.yml used for Wordmove**
[movefile.txt](https://github.com/welaika/docker-wordmove/files/3352424/movefile.txt)

**Wordmove Doctor**
> $ docker exec CONTAINER wordmove doctor
[Alpine Doctor Error.txt](https://github.com/welaika/docker-wordmove/files/3352403/alpine.error.txt)

**Pulling DB into Working Container**
>  $ docker exec CONTAINER wordmove pull -e stg -d
[Alpine pull d Error.txt](https://github.com/welaika/docker-wordmove/files/3352411/Alpine.pull.d.Error.txt)

Kernel Version: 4.19.55-2-lts
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64

Server Version: 18.09.7-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs

I think this is an awesome project and I am hugely grateful for the team of devs hard at work here. Thank you!

**Comment by alessandro-fazzi** [comment]
@Gadgitmatic as a maintainer it's really an open eyes dream to have these type of contributions. Kudos all the way down ❤️

**Comment by alessandro-fazzi** [comment]
It would be nice if you could run interactively your container and launch

```bash
apk add --no-cache php7-json php7-mbstring
```

then re-launch your test command.

Do you have the time to try this out?

**Comment by Gadgitmatic** [comment]
**That does the trick!** 
All seems to be working as expected now. Any way to incorporate this into a docker-compose file? If not, will the Apline image be updated with the dependencies?

**Comment by alessandro-fazzi** [comment]
I think that, seen your experience, this should be included in the base image. And I'd like to do that.

What do you think about @Gadgitmatic ?

**Comment by Gadgitmatic** [comment]
For sure!

Genuinely glad I can contribute (while still being a script kiddy). 😁

**Comment by alessandro-fazzi** [comment]
The update image is currently building on dockerhub.

Thanks again for your support!
