### ISSUE TITLE
Should wordmove have local en_US.UTF-8 and run ssh-agent?

### ISSUE THREAD

**Issue by alessandro-fazzi** [welaika/docker-wordmove#18]
A reference to this issue staled into the Wordmove's issue trakcer: https://github.com/welaika/wordmove/issues/589

**Comment by alexx855** [comment]
i think im having the same issue 
![image](https://user-images.githubusercontent.com/1799851/123705429-378ab380-d867-11eb-9067-53df46cfe643.png)

And patching the image like the issue seems to work

```
apt-get update \
        && apt-get install -y locales \
        && rm -r /var/lib/apt/lists/* \
        && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
        && locale-gen \
        && echo "export LC_ALL=en_US.UTF-8" >> ~/.bashrc \
        && echo "export LANG=en_US.UTF-8" >> ~/.bashrc \
        && echo "export LANGUAGE=en_US.UTF-8" >> ~/.bashrc \
        && echo "eval \`ssh-agent -s\`" >> ~/.bashrc
```

**Comment by alessandro-fazzi** [comment]
Fixed into `latest`/`php7` tags.

If someone would like to help porting this feature into `alpine` too I'll be glad to follow-up.

Keep also in mind that future release of wordmove will drop the `default` `sql_adapter`, actually circumventing encoding problems.

Cheers

/cc @alexx855
