### ISSUE TITLE
PHP version question

### ISSUE THREAD

**Issue by alessandro-fazzi** [welaika/docker-wordmove#2]
Better to update PHP to 7.x or to release another image with PHP 7?

Keeping only 5 sounds bad to me, or at least I always use >7 in our projects.

**Comment by simonbland** [comment]
I would also recommend to update to PHP 7.x, for this image, but in a a new version/tag, for the reasons explained in [issue 8](https://github.com/welaika/docker-wordmove/issues/8). What do you think?

**Comment by alessandro-fazzi** [comment]
I'm with you, but I'd like to have the stable on PHP7 and a tag for PHP5. Do you see drawbacks?

**Comment by simonbland** [comment]
We could do it this way also. I like the idea of having the latest version by default.

The only drawback I can see is that we will silently force PHP7 for users that have already downloaded the image, when they will pull from the repository. Users whose requires PHP5 and not PHP7, if they exists, will have their environment broken. But this is the risk when pulling from the `latest` tag anyway (the only tag we have for the moment). There is nothing we can do for this, except providing proper tags.

Until we agree on a definitive tagging scheme, and implement it, we could go for a tag named `php5` or `ubuntu-php5` for example, if you want.
